[package]
name = "bevy-technical-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8"

[features]
client = []
server = []

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"
